version: '3.8'

services:
  habitbot:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - habitbot-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./app/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - habitbot-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3020:3000"
    networks:
      - habitbot-network

  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - habitbot-network

  logstash:
    image: logstash:7.9.2
    ports:
      - "5044:5044"
    volumes:
      - ./app/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./app/data/bot.log:/usr/share/logstash/bot/bot.log
    networks:
      - habitbot-network

  kibana:
    image: kibana:7.9.2
    ports:
      - "5602:5601"
    networks:
      - habitbot-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - habitbot-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "01233210"
      POSTGRES_DB: HabitBot
    ports:
      - "5433:5433"
    networks:
      - habitbot-network

  flink-jobmanager:
    image: flink:latest
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - habitbot-network

  flink-taskmanager:
    image: flink:latest
    depends_on:
      - flink-jobmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
    command: taskmanager
    networks:
      - habitbot-network

networks:
  habitbot-network:
    driver: bridge
